#!/usr/bin/env bash
. ~/.curo/c/set_terminal_size

left_title="Curo : $1"
data_file="$2"

right_title="$( uptime )"

spacing=$(( COLUMNS - ${#left_title} - ${#right_title} - 2 ))

title="$( printf "%s%${spacing}s%s" "$left_title" "" "$right_title" )"

clear
echo " $title"
line="$( printf "%${COLUMNS}s" )"
printf "%s\n\n" "${line// /-}"

cat "$data_file"
rm "$data_file"

# vim: set ft=sh :
